language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"

install:
  - composer install

script: vendor/bin/phpunit --configuration tests/travis.xml

after_script:
  - php vendor/bin/coveralls -v